"""
train.py

Trains Logistic Regression, Random Forest, and XGBoost classifiers on the
7-day price-drop prediction task.

Input:
    ml/data/features.csv   — generated by build_features.py
    ml/data/labels.csv     — generated by create_labels.py

Output:
    ml/artifacts/price_drop_lr_v1.pkl          Logistic Regression model
    ml/artifacts/price_drop_rf_v1.pkl          Random Forest model
    ml/artifacts/price_drop_xgboost_v1.pkl     XGBoost (calibrated, production model)
    ml/artifacts/price_drop_xgboost_base_v1.pkl  Raw XGBoost base estimator (for SHAP)
    ml/artifacts/feature_columns_v1.json       Contract: exact columns used at training time.
                                               The backend predictor reads this to guarantee
                                               it produces the same features at inference time.
    ml/artifacts/metrics_v1.json               Hold-out test set evaluation results.

Train / test split
------------------
We sort all observations by observed_at and use the first 80% as training,
the last 20% as test. This time-based split is non-negotiable: a random split
would let the model train on future data and be evaluated on past data, giving
misleadingly optimistic metrics in development but failing silently in production.

NaN strategy
------------
Rolling features (e.g. price_std_7d) are NaN for early observations that don't
have enough prior data. We fill with -1, a value outside the valid range of
every feature. This preserves the cold-start signal: a product with no prior
history should look different from a product with stable history, not like an
average product (which median imputation would produce).

Class imbalance
---------------
class_weight='balanced' instructs sklearn to weight each positive training
example by n_negative / n_positive. This ensures rare price-drop events have
equal influence on the loss function as the more common no-drop events.

XGBoost tuning
--------------
RandomizedSearchCV samples random combinations from a parameter grid and picks
the best using TimeSeriesSplit cross-validation. TimeSeriesSplit always validates
on data that comes after the training fold — regular k-fold would shuffle
observations randomly, creating the same future-leakage problem as a random
train/test split.

XGBoost calibration
-------------------
XGBoost probabilities can be overconfident (pushed toward 0 and 1). We apply
CalibratedClassifierCV(cv='prefit', method='sigmoid') on a small held-out
calibration set. 'prefit' means we train XGBoost first, then fit only the thin
sigmoid correction layer — keeping the base model intact for SHAP. The base
model is saved separately as price_drop_xgboost_base_v1.pkl.

Usage:
    cd /path/to/PriceDropOS
    python ml/src/train.py                   # train all models
    python ml/src/train.py --model xgb       # xgboost only
    python ml/src/train.py --model rf        # random_forest only
    python ml/src/train.py --model lr        # logistic_regression only
"""
import argparse
import json
import logging
import sys
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.calibration import CalibratedClassifierCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import RandomizedSearchCV, TimeSeriesSplit
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score, f1_score, precision_score, recall_score,
    roc_auc_score, average_precision_score,
)
from xgboost import XGBClassifier

logger = logging.getLogger(__name__)

TRAIN_SPLIT    = 0.80    # fraction of observations (by time) used for training
NAN_FILL       = -1.0    # sentinel for missing rolling features
VERSION        = "v1"

# Exact columns used for training — saved to feature_columns_v1.json.
# The backend predictor must produce exactly these columns at inference time.
FEATURE_COLS = [
    "price",
    "price_avg_7d",
    "price_avg_14d",
    "price_avg_30d",
    "price_min_7d",
    "price_min_30d",
    "price_max_7d",
    "price_max_30d",
    "price_std_7d",
    "price_std_30d",
    "price_vs_avg_30d_pct",
    "price_vs_min_30d_pct",
    "price_vs_max_30d_pct",
    "price_change_prev",
    "price_change_prev_pct",
    "num_drops_7d",
    "num_drops_30d",
    "days_since_last_drop",
    "observation_count",
    "day_of_week",
    "is_weekend",
    "month",
    "week_of_year",
]

MODELS = {
    # LR requires feature scaling: 'price' (~$300) vs 'is_weekend' (0/1) are on wildly
    # different scales. Without scaling, the optimizer weights large-magnitude features
    # disproportionately and may never converge. Pipeline ensures the scaler is saved
    # alongside the model so inference uses the same transform automatically.
    "lr": (
        "logistic_regression",
        Pipeline([
            ("scaler", StandardScaler()),
            ("clf", LogisticRegression(class_weight="balanced", max_iter=2000, random_state=42)),
        ]),
    ),
    # RF splits one feature at a time — scale doesn't affect which split is optimal.
    "rf": (
        "random_forest",
        RandomForestClassifier(
            n_estimators=200,
            max_depth=8,
            min_samples_leaf=2,
            class_weight="balanced",
            random_state=42,
            n_jobs=-1,
        ),
    ),
    # XGBoost uses gradient boosting: each tree corrects the previous tree's mistakes.
    # Trained via hyperparameter search + calibrated for trustworthy probabilities.
    # The base estimator is also saved separately for SHAP explanations.
    "xgb": None,  # handled by train_xgboost() — not a simple fit() call
}

# Parameter space for XGBoost hyperparameter search.
_XGB_PARAM_GRID = {
    "n_estimators":     [50, 100, 200, 300],
    "max_depth":        [2, 3, 4, 5, 6],
    "learning_rate":    [0.01, 0.05, 0.1, 0.2, 0.3],
    "subsample":        [0.6, 0.7, 0.8, 1.0],
    "colsample_bytree": [0.6, 0.7, 0.8, 1.0],
    "min_child_weight": [1, 2, 3, 5],
    "gamma":            [0, 0.1, 0.2, 0.5],
}


# ---------------------------------------------------------------------------
# Data loading + splitting
# ---------------------------------------------------------------------------

def load_and_merge(features_path: Path, labels_path: Path) -> pd.DataFrame:
    df_feat = pd.read_csv(features_path, parse_dates=["observed_at"])
    df_lab  = pd.read_csv(labels_path,   parse_dates=["observed_at"])

    # Keep only rows that can be correctly labeled
    df_lab = df_lab[df_lab["is_labelable"]].copy()

    df = df_feat.merge(df_lab[["id", "label_drop_7d"]], on="id", how="inner")

    logger.info(
        "Merged dataset: %d rows | %d products | positive rate %.1f%%",
        len(df),
        df["product_id"].nunique(),
        df["label_drop_7d"].mean() * 100,
    )
    return df


def time_split(df: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Sort by observed_at, use the first TRAIN_SPLIT fraction as training data
    and the rest as the hold-out test set.

    All training examples are chronologically earlier than all test examples.
    """
    df_sorted = df.sort_values("observed_at").reset_index(drop=True)
    cutoff_idx  = int(len(df_sorted) * TRAIN_SPLIT)
    cutoff_time = df_sorted["observed_at"].iloc[cutoff_idx]

    df_train = df_sorted.iloc[:cutoff_idx].copy()
    df_test  = df_sorted.iloc[cutoff_idx:].copy()

    logger.info(
        "Time split — train: %d rows (before %s) | test: %d rows (from %s)",
        len(df_train), cutoff_time.date(),
        len(df_test),  cutoff_time.date(),
    )
    return df_train, df_test


def prepare_xy(df: pd.DataFrame) -> tuple[pd.DataFrame, np.ndarray]:
    """Select feature columns, fill NaN, return X DataFrame and y array.
    Returning a DataFrame (not .values) lets sklearn store feature names in
    the model — inference can then pass named DataFrames without warnings."""
    available = [c for c in FEATURE_COLS if c in df.columns]
    missing   = [c for c in FEATURE_COLS if c not in df.columns]
    if missing:
        logger.warning("Feature columns missing from dataset (will be filled with %s): %s", NAN_FILL, missing)

    X = df[available].copy()
    for col in missing:
        X[col] = NAN_FILL

    X = X[FEATURE_COLS].fillna(NAN_FILL)
    y = df["label_drop_7d"].astype(int).values
    return X, y


# ---------------------------------------------------------------------------
# Training + evaluation
# ---------------------------------------------------------------------------

def evaluate(model, X_test: np.ndarray, y_test: np.ndarray) -> dict:
    y_pred  = model.predict(X_test)
    y_proba = model.predict_proba(X_test)[:, 1]

    metrics = {
        "accuracy":          round(accuracy_score(y_test, y_pred),          4),
        "precision":         round(precision_score(y_test, y_pred,          zero_division=0), 4),
        "recall":            round(recall_score(y_test, y_pred,             zero_division=0), 4),
        "f1":                round(f1_score(y_test, y_pred,                 zero_division=0), 4),
        "roc_auc":           round(roc_auc_score(y_test, y_proba)           if len(set(y_test)) > 1 else 0.0, 4),
        "pr_auc":            round(average_precision_score(y_test, y_proba) if len(set(y_test)) > 1 else 0.0, 4),
        "n_train":           None,   # filled by caller
        "n_test":            int(len(y_test)),
        "positive_rate_test": round(float(y_test.mean()), 4),
    }
    return metrics


def train_model(
    model_key: str,
    df_train: pd.DataFrame,
    df_test:  pd.DataFrame,
    artifacts_dir: Path,
) -> dict:
    model_name, clf = MODELS[model_key]

    X_train, y_train = prepare_xy(df_train)
    X_test,  y_test  = prepare_xy(df_test)

    logger.info("Training %s on %d examples (%d positive)…", model_name, len(y_train), y_train.sum())
    clf.fit(X_train, y_train)

    metrics = evaluate(clf, X_test, y_test)
    metrics["n_train"] = int(len(y_train))

    logger.info(
        "%s — acc=%.3f prec=%.3f rec=%.3f f1=%.3f roc_auc=%.3f pr_auc=%.3f",
        model_name,
        metrics["accuracy"], metrics["precision"], metrics["recall"],
        metrics["f1"], metrics["roc_auc"], metrics["pr_auc"],
    )

    artifact_path = artifacts_dir / f"price_drop_{model_name}_{VERSION}.pkl"
    joblib.dump(clf, artifact_path)
    logger.info("Saved model artifact: %s", artifact_path)

    return metrics


def train_xgboost(
    df_train: pd.DataFrame,
    df_test:  pd.DataFrame,
    artifacts_dir: Path,
) -> dict:
    """
    Train XGBoost with:
      1. Hyperparameter search (RandomizedSearchCV + TimeSeriesSplit)
      2. Calibration (CalibratedClassifierCV, cv=3, method='sigmoid')
      3. Save both the calibrated model and the raw base model for SHAP

    TimeSeriesSplit is used instead of regular k-fold so validation folds
    always come after their training folds — no future data leaks into the past.

    We run hyperparameter search first (produces tuned_xgb, saved for SHAP), then
    create a fresh unfitted estimator with the same params and pass it to
    CalibratedClassifierCV(cv=3). cv='prefit' was removed in scikit-learn 1.8.0.
    """
    X_train_full, y_train_full = prepare_xy(df_train)
    X_test,       y_test       = prepare_xy(df_test)

    # --- Step 1: hyperparameter search ---
    # TimeSeriesSplit(n_splits=3): fold 1 trains on first 33%, validates on next 33%;
    # fold 2 trains on first 66%, validates on last 33%; always forward in time.
    pos_weight = int((y_train_full == 0).sum() / max((y_train_full == 1).sum(), 1))

    base_xgb = XGBClassifier(
        objective="binary:logistic",
        eval_metric="aucpr",
        scale_pos_weight=pos_weight,
        random_state=42,
        n_jobs=-1,
    )

    tscv = TimeSeriesSplit(n_splits=3)
    search = RandomizedSearchCV(
        base_xgb,
        param_distributions=_XGB_PARAM_GRID,
        n_iter=20,
        scoring="average_precision",
        cv=tscv,
        random_state=42,
        n_jobs=-1,
        refit=True,         # refit best params on full training set after search
    )

    logger.info("XGBoost: running hyperparameter search (20 iterations × 3 folds)…")
    search.fit(X_train_full, y_train_full)

    best_params = search.best_params_
    best_cv_score = search.best_score_
    logger.info("XGBoost best params: %s", best_params)
    logger.info("XGBoost best CV PR-AUC: %.4f", best_cv_score)

    # Refitted estimator on the full training set — kept as the SHAP base model
    tuned_xgb = search.best_estimator_

    # --- Step 2: calibration ---
    # CalibratedClassifierCV with cv=3 internally trains 3 copies of the estimator
    # (each on a different fold) and fits a sigmoid layer on top. We pass a fresh
    # estimator with the tuned params rather than the already-fitted one, since
    # CalibratedClassifierCV needs to control the fitting itself for cross-validation.
    # The separately saved tuned_xgb is what the predictor uses for SHAP.
    fresh_xgb = XGBClassifier(
        objective="binary:logistic",
        eval_metric="aucpr",
        scale_pos_weight=pos_weight,
        random_state=42,
        n_jobs=-1,
        **best_params,
    )
    calibrated_xgb = CalibratedClassifierCV(fresh_xgb, cv=3, method="sigmoid")
    calibrated_xgb.fit(X_train_full, y_train_full)

    # --- Step 3: evaluate on test set ---
    metrics = evaluate(calibrated_xgb, X_test, y_test)
    metrics["n_train"]    = int(len(y_train_full))
    metrics["best_params"] = best_params
    metrics["best_cv_pr_auc"] = round(best_cv_score, 4)

    logger.info(
        "xgboost — acc=%.3f prec=%.3f rec=%.3f f1=%.3f roc_auc=%.3f pr_auc=%.3f",
        metrics["accuracy"], metrics["precision"], metrics["recall"],
        metrics["f1"], metrics["roc_auc"], metrics["pr_auc"],
    )

    # --- Step 4: save artifacts ---
    # Calibrated model: used at inference time for predict_proba
    calibrated_path = artifacts_dir / f"price_drop_xgboost_{VERSION}.pkl"
    joblib.dump(calibrated_xgb, calibrated_path)
    logger.info("Saved calibrated XGBoost: %s", calibrated_path)

    # Base model: used by the backend predictor for SHAP explanations
    base_path = artifacts_dir / f"price_drop_xgboost_base_{VERSION}.pkl"
    joblib.dump(tuned_xgb, base_path)
    logger.info("Saved XGBoost base model (for SHAP): %s", base_path)

    return metrics


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")

    parser = argparse.ArgumentParser(description="Train price-drop prediction models")
    parser.add_argument(
        "--model", choices=["lr", "rf", "xgb", "all"], default="all",
        help="Which model to train (default: all)",
    )
    parser.add_argument("--features", default="ml/data/features.csv")
    parser.add_argument("--labels",   default="ml/data/labels.csv")
    parser.add_argument("--artifacts", default="ml/artifacts")
    args = parser.parse_args()

    features_path  = Path(args.features)
    labels_path    = Path(args.labels)
    artifacts_dir  = Path(args.artifacts)
    artifacts_dir.mkdir(parents=True, exist_ok=True)

    if not features_path.exists():
        logger.error("features.csv not found. Run: python ml/src/build_features.py")
        sys.exit(1)
    if not labels_path.exists():
        logger.error("labels.csv not found. Run: python ml/src/create_labels.py")
        sys.exit(1)

    df = load_and_merge(features_path, labels_path)

    if len(df) < 20:
        logger.error(
            "Only %d labelable rows. Need more price history. "
            "Run: cd backend && python -m app.db.seed",
            len(df),
        )
        sys.exit(1)

    df_train, df_test = time_split(df)

    # Save feature columns — the inference contract
    columns_path = artifacts_dir / f"feature_columns_{VERSION}.json"
    with open(columns_path, "w") as f:
        json.dump(FEATURE_COLS, f, indent=2)
    logger.info("Saved feature columns: %s", columns_path)

    keys_to_train = ["lr", "rf", "xgb"] if args.model == "all" else [args.model]
    all_metrics: dict[str, dict] = {}

    for key in keys_to_train:
        if key == "xgb":
            metrics = train_xgboost(df_train, df_test, artifacts_dir)
            all_metrics["xgboost"] = metrics
        else:
            metrics = train_model(key, df_train, df_test, artifacts_dir)
            model_name = MODELS[key][0]
            all_metrics[model_name] = metrics

    metrics_path = artifacts_dir / f"metrics_{VERSION}.json"
    with open(metrics_path, "w") as f:
        json.dump(all_metrics, f, indent=2)
    logger.info("Saved metrics: %s", metrics_path)

    print("\n=== Training complete ===")
    print(f"{'Model':<25} {'Acc':>6} {'Prec':>6} {'Rec':>6} {'F1':>6} {'ROC-AUC':>8} {'PR-AUC':>7}")
    print("-" * 70)
    for name, m in all_metrics.items():
        print(
            f"{name:<25} {m['accuracy']:>6.3f} {m['precision']:>6.3f} {m['recall']:>6.3f} "
            f"{m['f1']:>6.3f} {m['roc_auc']:>8.3f} {m['pr_auc']:>7.3f}"
        )
    print(f"\nTest set: {df_test['label_drop_7d'].mean():.1%} positive rate | {len(df_test)} rows")
    print("\nArtifacts saved to:", artifacts_dir.resolve())


if __name__ == "__main__":
    main()
